import type { Candidate } from '../api/client';

/**
 * TavernPNG 导出：将角色数据编码为 SillyTavern V2 格式，
 * 写入 PNG tEXt chunk (key: "chara")，生成可下载的 PNG 文件。
 */

// SillyTavern V2 character card spec
interface TavernV2Card {
  spec: 'chara_card_v2';
  spec_version: '2.0';
  data: {
    name: string;
    description: string;
    personality: string;
    scenario: string;
    first_mes: string;
    mes_example: string;
    system_prompt: string;
    post_history_instructions: string;
    creator: string;
    creator_notes: string;
    character_version: string;
    tags: string[];
    alternate_greetings: string[];
    extensions: Record<string, unknown>;
  };
}

function candidateToTavernV2(candidate: Candidate, language: string): TavernV2Card {
  const spec = candidate.spec_long as Record<string, string>;

  const name = spec.identity || spec.name || 'Character';
  const personality = spec.personality || '';
  const background = spec.background || '';
  const appearance = spec.appearance || '';
  const voice = spec.voice || '';
  const goals = spec.goals || '';
  const conflicts = spec.conflicts || '';
  const values = spec.values || '';
  const habits = spec.habits || '';
  const skills = spec.skills || '';
  const taboos = spec.taboos || '';
  const relationships = spec.relationships || '';
  const catchphrases = spec.catchphrases || spec.catchphrase || '';
  const openingLine = spec.opening_line || '';
  const dialogueExamples = spec.dialogue_examples || '';
  const systemConstraints = spec.system_constraints || '';
  const usageNotes = spec.usage_notes || '';

  // Build description from natural text + structured fields
  const descParts: string[] = [];
  if (candidate.natural_long) descParts.push(candidate.natural_long);
  if (appearance) descParts.push(`[Appearance]\n${appearance}`);
  if (background) descParts.push(`[Background]\n${background}`);
  if (relationships) descParts.push(`[Relationships]\n${relationships}`);
  if (habits) descParts.push(`[Habits]\n${habits}`);
  if (skills) descParts.push(`[Skills]\n${skills}`);
  if (values) descParts.push(`[Values]\n${values}`);
  if (taboos) descParts.push(`[Taboos]\n${taboos}`);

  // Build personality section
  const personalityParts: string[] = [];
  if (personality) personalityParts.push(personality);
  if (conflicts) personalityParts.push(`Inner conflicts: ${conflicts}`);
  if (goals) personalityParts.push(`Goals: ${goals}`);

  // Build scenario (voice + catchphrases)
  const scenarioParts: string[] = [];
  if (voice) scenarioParts.push(`Speech style: ${voice}`);
  if (catchphrases) scenarioParts.push(`Catchphrases: ${catchphrases}`);

  // Build example messages
  let mesExample = '';
  if (dialogueExamples) {
    mesExample = dialogueExamples;
  }

  return {
    spec: 'chara_card_v2',
    spec_version: '2.0',
    data: {
      name,
      description: descParts.join('\n\n'),
      personality: personalityParts.join('\n'),
      scenario: scenarioParts.join('\n'),
      first_mes: openingLine,
      mes_example: mesExample,
      system_prompt: systemConstraints,
      post_history_instructions: usageNotes,
      creator: 'RolerZ',
      creator_notes: `Generated by RolerZ (${language}). Score: ${Math.round(candidate.score * 100)}/100`,
      character_version: '1.0',
      tags: candidate.tags || [],
      alternate_greetings: [],
      extensions: {},
    },
  };
}

// ── PNG encoding helpers ──

function crc32(buf: Uint8Array): number {
  let crc = -1;
  for (let i = 0; i < buf.length; i++) {
    crc = (crc >>> 8) ^ crc32Table[(crc ^ buf[i]) & 0xff];
  }
  return (crc ^ -1) >>> 0;
}

const crc32Table = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[n] = c;
  }
  return table;
})();

function createTEXtChunk(keyword: string, text: string): Uint8Array {
  const keyBytes = new TextEncoder().encode(keyword);
  const textBytes = new TextEncoder().encode(text);
  // data = keyword + null separator + text
  const data = new Uint8Array(keyBytes.length + 1 + textBytes.length);
  data.set(keyBytes, 0);
  data[keyBytes.length] = 0; // null separator
  data.set(textBytes, keyBytes.length + 1);

  const type = new TextEncoder().encode('tEXt');
  // chunk: length(4) + type(4) + data + crc(4)
  const chunk = new Uint8Array(4 + 4 + data.length + 4);
  const view = new DataView(chunk.buffer);

  // Length
  view.setUint32(0, data.length, false);
  // Type
  chunk.set(type, 4);
  // Data
  chunk.set(data, 8);
  // CRC over type + data
  const crcData = new Uint8Array(4 + data.length);
  crcData.set(type, 0);
  crcData.set(data, 4);
  view.setUint32(8 + data.length, crc32(crcData), false);

  return chunk;
}

async function generateCardImage(name: string, tags: string[], score: number): Promise<Uint8Array> {
  const canvas = document.createElement('canvas');
  canvas.width = 400;
  canvas.height = 600;
  const ctx = canvas.getContext('2d')!;

  // Background gradient
  const grad = ctx.createLinearGradient(0, 0, 400, 600);
  grad.addColorStop(0, '#1e3a5f');
  grad.addColorStop(0.5, '#0f2847');
  grad.addColorStop(1, '#0a1929');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, 400, 600);

  // Decorative border
  ctx.strokeStyle = 'rgba(96, 165, 250, 0.3)';
  ctx.lineWidth = 2;
  ctx.roundRect(12, 12, 376, 576, 16);
  ctx.stroke();

  ctx.strokeStyle = 'rgba(96, 165, 250, 0.15)';
  ctx.lineWidth = 1;
  ctx.roundRect(20, 20, 360, 560, 12);
  ctx.stroke();

  // Decorative circles
  ctx.fillStyle = 'rgba(96, 165, 250, 0.06)';
  ctx.beginPath();
  ctx.arc(320, 80, 120, 0, Math.PI * 2);
  ctx.fill();
  ctx.beginPath();
  ctx.arc(80, 500, 100, 0, Math.PI * 2);
  ctx.fill();

  // Header line
  const headerGrad = ctx.createLinearGradient(40, 0, 360, 0);
  headerGrad.addColorStop(0, 'rgba(96, 165, 250, 0.6)');
  headerGrad.addColorStop(1, 'rgba(34, 211, 238, 0.6)');
  ctx.strokeStyle = headerGrad;
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(40, 90);
  ctx.lineTo(360, 90);
  ctx.stroke();

  // "PERSONA CARD" label
  ctx.fillStyle = 'rgba(96, 165, 250, 0.7)';
  ctx.font = '600 11px "Inter", "SF Pro Display", system-ui, sans-serif';
  ctx.letterSpacing = '4px';
  ctx.fillText('PERSONA CARD', 40, 70);

  // Character name
  ctx.fillStyle = '#e2e8f0';
  ctx.font = '700 32px "Noto Serif SC", "Inter", serif';
  ctx.letterSpacing = '0px';

  // Word wrap for long names
  const maxWidth = 320;
  const nameLines = wrapText(ctx, name, maxWidth);
  let nameY = 135;
  for (const line of nameLines) {
    ctx.fillText(line, 40, nameY);
    nameY += 42;
  }

  // Score badge
  const scorePct = Math.round(score * 100);
  const scoreX = 40;
  const scoreY = nameY + 20;
  const scoreColor = score > 0.7 ? '#10b981' : score > 0.42 ? '#f59e0b' : '#6b7280';

  ctx.fillStyle = scoreColor + '20';
  ctx.beginPath();
  ctx.roundRect(scoreX, scoreY - 18, 80, 28, 14);
  ctx.fill();
  ctx.strokeStyle = scoreColor + '40';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.roundRect(scoreX, scoreY - 18, 80, 28, 14);
  ctx.stroke();

  ctx.fillStyle = scoreColor;
  ctx.font = '700 14px "Inter", system-ui, sans-serif';
  ctx.fillText(`${scorePct} / 100`, scoreX + 12, scoreY + 2);

  // Tags
  const tagY = scoreY + 40;
  let tagX = 40;
  let currentTagY = tagY;
  ctx.font = '500 12px "Inter", system-ui, sans-serif';

  for (const tag of tags.slice(0, 8)) {
    const tw = ctx.measureText(tag).width + 20;
    if (tagX + tw > 360) {
      tagX = 40;
      currentTagY += 30;
    }

    ctx.fillStyle = 'rgba(96, 165, 250, 0.1)';
    ctx.beginPath();
    ctx.roundRect(tagX, currentTagY - 14, tw, 24, 12);
    ctx.fill();
    ctx.strokeStyle = 'rgba(96, 165, 250, 0.25)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.roundRect(tagX, currentTagY - 14, tw, 24, 12);
    ctx.stroke();

    ctx.fillStyle = 'rgba(148, 196, 255, 0.9)';
    ctx.fillText(tag, tagX + 10, currentTagY + 2);

    tagX += tw + 8;
  }

  // Footer
  ctx.fillStyle = 'rgba(96, 165, 250, 0.4)';
  ctx.font = '600 10px "Inter", system-ui, sans-serif';
  ctx.letterSpacing = '3px';
  ctx.fillText('ROLERZ', 40, 560);

  ctx.fillStyle = 'rgba(96, 165, 250, 0.25)';
  ctx.font = '400 10px "Inter", system-ui, sans-serif';
  ctx.letterSpacing = '0px';
  ctx.fillText('Character Forge', 110, 560);

  // Footer line
  ctx.strokeStyle = 'rgba(96, 165, 250, 0.2)';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(40, 540);
  ctx.lineTo(360, 540);
  ctx.stroke();

  // Convert to PNG bytes
  const blob = await new Promise<Blob>((resolve) =>
    canvas.toBlob((b) => resolve(b!), 'image/png')
  );
  return new Uint8Array(await blob.arrayBuffer());
}

function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const lines: string[] = [];
  let current = '';
  for (const char of text) {
    const test = current + char;
    if (ctx.measureText(test).width > maxWidth && current) {
      lines.push(current);
      current = char;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines.length > 0 ? lines : [text];
}

function injectTEXtIntoPNG(pngBytes: Uint8Array, keyword: string, text: string): Uint8Array {
  // PNG structure: signature(8) + IHDR chunk + ... + IEND chunk
  // Insert tEXt chunk before IEND
  const iendOffset = findChunkOffset(pngBytes, 'IEND');
  if (iendOffset < 0) throw new Error('Invalid PNG: IEND not found');

  const textChunk = createTEXtChunk(keyword, text);

  const result = new Uint8Array(pngBytes.length + textChunk.length);
  result.set(pngBytes.subarray(0, iendOffset), 0);
  result.set(textChunk, iendOffset);
  result.set(pngBytes.subarray(iendOffset), iendOffset + textChunk.length);

  return result;
}

function findChunkOffset(png: Uint8Array, type: string): number {
  const typeBytes = new TextEncoder().encode(type);
  // Skip PNG signature (8 bytes)
  let offset = 8;
  while (offset < png.length - 8) {
    const view = new DataView(png.buffer, png.byteOffset + offset);
    const length = view.getUint32(0, false);
    // Check type at offset + 4
    if (
      png[offset + 4] === typeBytes[0] &&
      png[offset + 5] === typeBytes[1] &&
      png[offset + 6] === typeBytes[2] &&
      png[offset + 7] === typeBytes[3]
    ) {
      return offset;
    }
    // Move to next chunk: length(4) + type(4) + data(length) + crc(4)
    offset += 12 + length;
  }
  return -1;
}

export async function exportTavernPNG(candidate: Candidate, language: string): Promise<void> {
  const card = candidateToTavernV2(candidate, language);
  const cardJson = JSON.stringify(card);
  const cardBase64 = btoa(unescape(encodeURIComponent(cardJson)));

  const spec = candidate.spec_long as Record<string, string>;
  const name = spec.identity || spec.name || 'Character';

  // Generate card image
  const pngBytes = await generateCardImage(name, candidate.tags || [], candidate.score);

  // Inject tEXt chunk with character data
  const finalPng = injectTEXtIntoPNG(pngBytes, 'chara', cardBase64);

  // Download
  const blob = new Blob([finalPng as unknown as BlobPart], { type: 'image/png' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${name.replace(/[^a-zA-Z0-9\u4e00-\u9fff]/g, '_')}.png`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
